name: API Test Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: 
     - cron: 00 14 * * * 

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests with Maven
      run: mvn clean test -Dsuite=suite -X

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with: 
        name: Archiving the Logs & Results
        path: |
          logs/
          target/surefire-reports

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit

        
      

